### PR TITLE
Always use the path of the url

### LINKED ISSUE #1: getUrl() is there but | fileExists is false
Newest Craft. 
Newsst Plugin.

```
{{ d(opt.image.getUrl()) }}
{{ d(opt.image.getUrl() | fileExists) }}
{% if opt.image.getUrl() | fileExists %}
...
{% endif %}

![image](https://user-images.githubusercontent.com/764292/68743056-e4acab80-05f1-11ea-9217-8a330338f3e6.png)

Strange :)

### PR DESCRIPTION
**Pull request by davidhellmann**
Fix https://github.com/moresoda/existential/issues/1

### CODE REVIEW

**Comment by davidhellmann** [comment]
@fantasticmachine can u release it? That would be nice :)

**Comment by peteeveleigh** [comment]
Argh! Sorry. I totally forgot about it. Will go and find out what I need to do later today.

Pete

**Comment by peteeveleigh** [comment]
Done!

**Comment by davidhellmann** [comment]
```
Problem 1
    - The requested package moresoda/existential could not be found in any version, there may be a typo in the package name.
```
🤔

**Pull request merged**
