### PR TITLE
Craft v4 update

### PR DESCRIPTION
**Pull request by tyssen**
First time I've done any plugin work for v4 or a PR for that matter, so hope I've go this right.

### CODE REVIEW

**Review by peteeveleigh — APPROVED** [review]

**Comment by peteeveleigh** [comment]
Thanks @tyssen. I really appreciate your help and apologies for not getting to this myself.
I've merged in this PR

**Comment by tyssen** [comment]
Is there something else you need to do on the Craft end? Because when I check the upgrade page in my site's control panel, it still says _Not Ready_.

**Comment by peteeveleigh** [comment]
Ah yes, I’ll need to tag a release for it. Will do that today

**Comment by peteeveleigh** [comment]
You should now find your update is available. Thanks for doing that :)

**Comment by tyssen** [comment]
Sorry, took me a while to get back to this. This is what I'm seeing in the Craft CP:

image

**Comment by tyssen** [comment]
Hi @peteeveleigh Craft 4 updates page is still showing it as being not ready.

**Comment by peteeveleigh** [comment]
@tyssen Ugh, sorry. I don't know what is going on with this. I'll try and take a look later and nuke it from orbit or something.

**Pull request merged**
